const assert=require('node:assert/strict');
const {gs,login,sheets,advanceTime}=require('./store-fixture.cjs');
const a=login('A1B2','student-a-12345678901234','a','홍길동'),b=login('A1B2','student-b-12345678901234','b','김학생'),teacher=login('T1E2','teacher-a-12345678901234','t','담임');
const other=login('B1C2','student-c-12345678901234','c','홍길동');
for(const r of[a,b,teacher,other])assert.equal(r.ok,true);
assert.equal(login('A1B2','student-d-12345678901234','d',' 홍길동 ').status,409);
const ascii=login('A1B2','student-e-12345678901234','e','Test');assert.equal(ascii.ok,true);
assert.equal(login('A1B2','student-f-12345678901234','f','ＴＥＳＴ').status,409);
const teacherPhone=login('T1E2','teacher-b-12345678901234','t2','담임');assert.equal(teacherPhone.ok,true);assert.equal(gs({action:'session',token:teacher.token}).ok,true);
function act(who,action,fields={}){return gs({token:who.token,action,...fields});}
const g=act(a,'createGroup',{name:'탐험조'}).myGroup;assert.ok(g.id);
assert.equal(act(b,'joinGroup',{groupId:g.id}).ok,true);
let r=act(a,'setGroupLocation',{groupId:g.id,x:1330,y:632});assert.equal(r.myGroup.location.x,1330);assert.equal(r.myGroup.location.updatedBy,'홍길동');
assert.equal(act(teacher,'groups').groups[0].location.y,632);
assert.equal(act(other,'groups').groups.length,0);
assert.equal(act(other,'setGroupLocation',{groupId:g.id,x:10,y:10}).status,403);
assert.equal(act(teacher,'setGroupLocation',{groupId:g.id,x:10,y:10}).status,403);
for(const x of[-1,2305,1.5,'50'])assert.equal(act(a,'setGroupLocation',{groupId:g.id,x,y:10}).ok,false);
assert.equal(act(b,'setGroupLocation',{groupId:g.id,x:1500,y:700}).myGroup.location.x,1500);
assert.equal(sheets.GroupLocations.data.length,2);
assert.equal(act(teacher,'clearGroupLocation',{groupId:g.id}).groups[0].location,null);
act(a,'setGroupLocation',{groupId:g.id,x:1300,y:600});
assert.equal(act(a,'logout').ok,true);
assert.equal(login('A1B2','student-a-12345678901234','a','홍길동2').status,409,'device id alone cannot reclaim a student');
const recovery=act(teacher,'createRecovery',{deviceId:a.user.deviceId,newRecoveryToken:'a'.repeat(64)});assert.equal(recovery.ok,true);const restoredToken='b'.repeat(64),renamed={...gs({action:'consumeRecovery',recoveryToken:recovery.recoveryToken,newToken:restoredToken}),token:restoredToken};assert.equal(renamed.ok,true);
assert.equal(act(renamed,'groups').myGroup.id,g.id);assert.ok(act(renamed,'groups').myGroup.members.includes('홍길동'));
assert.equal(act(a,'session').status,401);
assert.equal(act(b,'removeClassMember',{deviceId:renamed.user.deviceId}).status,403);
assert.equal(act(teacher,'removeClassMember',{deviceId:other.user.deviceId}).status,403);
assert.equal(act(teacher,'removeClassMember',{deviceId:teacher.user.deviceId}).ok,false);
r=act(teacher,'removeClassMember',{deviceId:renamed.user.deviceId});assert.equal(r.ok,true);assert.ok(!r.people.some(p=>p.deviceId===renamed.user.deviceId));
assert.equal(act(renamed,'session').status,401);
assert.equal(login('A1B2','student-new-12345678901','new','홍길동2').ok,true);
assert.equal(act(other,'session').ok,true);
act(teacher,'assignMember',{deviceId:b.user.deviceId,groupId:null});
assert.equal(act(b,'setGroupLocation',{groupId:g.id,x:20,y:20}).status,403);
assert.equal(act(teacher,'groups').groups[0].location,null);
act(b,'joinGroup',{groupId:g.id});advanceTime(86400001);
// Refresh fixture token expiry to isolate location expiry from authentication expiry.
sheets.Sessions.data.slice(1).forEach(r=>r[5]+=86400001);
assert.equal(act(teacher,'groups').groups[0].location,null);
console.log('PASS backend: class isolation, student name uniqueness, teacher multi-device sessions, group retention, location permissions/expiry and teacher member deletion.');
