const assert=require('node:assert/strict'),crypto=require('node:crypto');const{gs,login,sheets,props,advanceTime}=require('./store-fixture.cjs');const secret=()=>crypto.randomBytes(32).toString('hex'),act=(who,action,args={})=>gs({token:who.token,action,...args});
const a=login('A1B2','recovery-student-a-12345678','a','학생 하나'),b=login('A1B2','recovery-student-b-12345678','b','학생 둘'),t=login('T1E2','recovery-teacher-a-12345678','t','선생님'),other=login('B1C2','recovery-other-1234567890','o','다른 반');
const group=act(a,'createGroup',{name:'1조'}).myGroup;const key=secret();delete sheets.RecoveryKeys;assert.equal(act(a,'registerRecovery',{recoveryToken:key}).ok,true);assert.notEqual(sheets.RecoveryKeys.data[1][0],key);assert.equal(act(b,'registerRecovery',{recoveryToken:key}).status,409);assert.equal(act(t,'registerRecovery',{recoveryToken:secret()}).status,403);
// Cookie loss retains group and a single identity, and replaces the old session.
const nt=secret(),res=gs({action:'resumeRecovery',recoveryToken:key,deviceId:a.user.deviceId,newToken:nt});assert.equal(res.ok,true);assert.equal(res.myGroup.id,group.id);assert.equal(res.user.nickname,'학생 하나');assert.equal(act(a,'session').status,401);a.token=nt;
assert.equal(gs({action:'resumeRecovery',recoveryToken:key,deviceId:b.user.deviceId,newToken:secret()}).status,401);
assert.equal(login('A1B2','different-device-1234567890','x','학생 하나').status,409);assert.equal(login('A1B2',a.user.deviceId,'x','사칭').status,409);
assert.equal(act(b,'createRecovery',{deviceId:a.user.deviceId,newRecoveryToken:secret()}).status,403);assert.equal(act(t,'createRecovery',{deviceId:other.user.deviceId,newRecoveryToken:secret()}).status,404);assert.equal(act(t,'createRecovery',{deviceId:t.user.deviceId,newRecoveryToken:secret()}).status,404);
function invite(who=a){return act(t,'createRecovery',{deviceId:who.user.deviceId,newRecoveryToken:secret()});}
const first=invite(),qr=invite();assert.equal(gs({action:'previewRecovery',recoveryToken:first.recoveryToken}).status,410);const preview=gs({action:'previewRecovery',recoveryToken:qr.recoveryToken});assert.equal(preview.nickname,'학생 하나');assert.equal(preview.deviceId,undefined);assert.equal(preview.classId,undefined);
const newToken=secret(),restored=gs({action:'consumeRecovery',recoveryToken:qr.recoveryToken,newToken,deviceId:other.user.deviceId,role:'teacher',classId:'class-b'});assert.equal(restored.ok,true);assert.equal(restored.user.deviceId,a.user.deviceId);assert.equal(restored.user.role,'student');assert.equal(restored.user.classId,'class-a');assert.equal(restored.myGroup.id,group.id);assert.equal(restored.myGroup.count,1);assert.equal(act(a,'session').status,401);assert.equal(gs({action:'resumeRecovery',recoveryToken:key,deviceId:a.user.deviceId,newToken:secret()}).status,410);assert.equal(gs({action:'consumeRecovery',recoveryToken:qr.recoveryToken,newToken:secret()}).status,410);a.token=newToken;
const key2=secret();assert.equal(act(a,'registerRecovery',{recoveryToken:key2}).ok,true);assert.equal(act(a,'logout').ok,true);assert.equal(gs({action:'resumeRecovery',recoveryToken:key2,deviceId:a.user.deviceId,newToken:secret()}).status,410);assert.ok(act(t,'groups').people.some(p=>p.deviceId===a.user.deviceId&&p.inactive));
const afterLogout=invite();assert.equal(afterLogout.ok,true);const nt2=secret();assert.equal(gs({action:'consumeRecovery',recoveryToken:afterLogout.recoveryToken,newToken:nt2}).ok,true);a.token=nt2;
const gone=invite();act(t,'removeClassMember',{deviceId:a.user.deviceId});assert.equal(gs({action:'consumeRecovery',recoveryToken:gone.recoveryToken,newToken:secret()}).status,410);assert.ok(!act(t,'groups').people.some(p=>p.deviceId===a.user.deviceId));assert.equal(login('A1B2','replacement-student-12345678','new','학생 하나').ok,true);
const exp=invite(b);advanceTime(600001);assert.equal(gs({action:'previewRecovery',recoveryToken:exp.recoveryToken}).status,410);
const stopped=invite(b);sheets.AccessCodes.data.find(r=>r[0]==='A1B2')[4]=false;assert.equal(gs({action:'consumeRecovery',recoveryToken:stopped.recoveryToken,newToken:secret()}).status,410);
(async()=>{const{handleRequest}=await import('../server/worker.mjs');const old=global.fetch;let sent;global.fetch=async(_,opts)=>{sent=JSON.parse(opts.body);return new Response(JSON.stringify({ok:true,user:{role:'student'}}));};try{const env={SHEETS_API_URL:'https://script.google.com/macros/s/mock/exec',SHEETS_BRIDGE_SECRET:props.BRIDGE_SECRET};const call=(endpoint,body,headers={})=>handleRequest(new Request('https://planner.test/api/recovery/'+endpoint,{method:'POST',headers:{origin:'https://planner.test','content-type':'application/json',...headers},body:JSON.stringify(body)}),env);
assert.equal((await call('create',{deviceId:b.user.deviceId})).status,401);assert.equal((await call('consume',{recoveryToken:'bad'})).status,400);assert.equal((await call('consume',{recoveryToken:secret()},{origin:'https://evil.test'})).status,403);const r=await call('consume',{recoveryToken:secret(),role:'teacher',classId:'class-b',deviceId:'spoof'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Lax.*Secure/);assert.equal(sent.role,undefined);assert.equal(sent.classId,undefined);assert.equal(sent.deviceId,undefined);assert.match(sent.newToken,/^[a-f0-9]{64}$/);
console.log('PASS recovery: cookie-loss restore, single-use teacher QR, expiry, class/role boundaries, old credential revocation, deliberate logout, persistent roster, name/device impersonation prevention and server-issued secure cookie.');}finally{global.fetch=old;}})().catch(e=>{console.error(e);process.exitCode=1;});
